# Generated by Django 4.2.30 on 2026-07-15 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_clients', to='businesses.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'client')},
            },
        ),
    ]
