# Generated by Django 4.2.30 on 2026-07-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_blockedclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Jedinstveni identifikacioni broj firme registrovane u BiH', max_length=30, null=True, unique=True, verbose_name='JIB / ID broj firme'),
        ),
    ]
