# Generated by Django 6.0.5 on 2026-05-11 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Na čekanju'), ('confirmed', 'Potvrđen'), ('cancelled_client', 'Otkazan od klijenta'), ('cancelled_business', 'Otkazan od salona'), ('completed', 'Završen'), ('no_show', 'Nije se pojavio')], default='pending', max_length=25)),
                ('client_notes', models.TextField(blank=True, help_text='Napomene klijenta')),
                ('internal_notes', models.TextField(blank=True, help_text='Interne napomene (vidljive samo biznisu)')),
                ('cancellation_reason', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('review_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
