# Generated by Django 4.2.30 on 2026-06-21 21:15

import apps.subscriptions.models
from decimal import Decimal
from django.db import migrations, models


def set_price_to_10(apps, schema_editor):
    Subscription = apps.get_model('subscriptions', 'Subscription')
    Subscription.objects.filter(monthly_price=Decimal('19.99')).update(monthly_price=Decimal('10.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=apps.subscriptions.models._default_price, max_digits=8),
        ),
        migrations.RunPython(set_price_to_10, migrations.RunPython.noop),
    ]
