# Generated by Django 4.2.30 on 2026-07-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_update_monthly_price_to_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
