# Generated by Django 6.0.5 on 2026-05-11 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('message_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_channel', models.CharField(choices=[('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], default='viber', max_length=20)),
                ('receive_confirmation', models.BooleanField(default=True)),
                ('receive_reminder_24h', models.BooleanField(default=True)),
                ('receive_reminder_2h', models.BooleanField(default=True)),
                ('receive_cancellation', models.BooleanField(default=True)),
                ('receive_marketing', models.BooleanField(default=False)),
                ('viber_available', models.BooleanField(default=False)),
                ('whatsapp_available', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
